name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
#          - ubuntu-latest
          - macOS-latest
#          - windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Meson
      run: pip install meson

#    - name: Install ninja (Ubuntu)
#      if: matrix.os == 'ubuntu-latest'
#      run: sudo apt-get install ninja-build

    - name: Install ninja (macOS)
      if: matrix.os == 'macOS-latest'
      run: brew install ninja

#    - name: Install ninja (Windows)
#      if: matrix.os == 'windows-latest'
#      run: scoop install ninja

    - name: Configure with Meson
      run: CC=gcc-9 CXX=g++-9 meson . build

    - name: Build and run tests
      run: ninja -C build test
